// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
namespace message {
class Metadata;
class MetadataDefaultTypeInternal;
extern MetadataDefaultTypeInternal _Metadata_default_instance_;
class UploadImageRequest;
class UploadImageRequestDefaultTypeInternal;
extern UploadImageRequestDefaultTypeInternal _UploadImageRequest_default_instance_;
class UploadImageResponse;
class UploadImageResponseDefaultTypeInternal;
extern UploadImageResponseDefaultTypeInternal _UploadImageResponse_default_instance_;
}  // namespace message
PROTOBUF_NAMESPACE_OPEN
template<> ::message::Metadata* Arena::CreateMaybeMessage<::message::Metadata>(Arena*);
template<> ::message::UploadImageRequest* Arena::CreateMaybeMessage<::message::UploadImageRequest>(Arena*);
template<> ::message::UploadImageResponse* Arena::CreateMaybeMessage<::message::UploadImageResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace message {

// ===================================================================

class UploadImageRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:message.UploadImageRequest) */ {
 public:
  inline UploadImageRequest() : UploadImageRequest(nullptr) {}
  virtual ~UploadImageRequest();

  UploadImageRequest(const UploadImageRequest& from);
  UploadImageRequest(UploadImageRequest&& from) noexcept
    : UploadImageRequest() {
    *this = ::std::move(from);
  }

  inline UploadImageRequest& operator=(const UploadImageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UploadImageRequest& operator=(UploadImageRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UploadImageRequest& default_instance();

  enum DataCase {
    kMetadata = 1,
    kChunkData = 2,
    DATA_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UploadImageRequest* internal_default_instance() {
    return reinterpret_cast<const UploadImageRequest*>(
               &_UploadImageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UploadImageRequest& a, UploadImageRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(UploadImageRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UploadImageRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UploadImageRequest* New() const final {
    return CreateMaybeMessage<UploadImageRequest>(nullptr);
  }

  UploadImageRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UploadImageRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UploadImageRequest& from);
  void MergeFrom(const UploadImageRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UploadImageRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "message.UploadImageRequest";
  }
  protected:
  explicit UploadImageRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMetadataFieldNumber = 1,
    kChunkDataFieldNumber = 2,
  };
  // .message.Metadata metadata = 1;
  bool has_metadata() const;
  private:
  bool _internal_has_metadata() const;
  public:
  void clear_metadata();
  const ::message::Metadata& metadata() const;
  ::message::Metadata* release_metadata();
  ::message::Metadata* mutable_metadata();
  void set_allocated_metadata(::message::Metadata* metadata);
  private:
  const ::message::Metadata& _internal_metadata() const;
  ::message::Metadata* _internal_mutable_metadata();
  public:
  void unsafe_arena_set_allocated_metadata(
      ::message::Metadata* metadata);
  ::message::Metadata* unsafe_arena_release_metadata();

  // bytes chunk_data = 2;
  private:
  bool _internal_has_chunk_data() const;
  public:
  void clear_chunk_data();
  const std::string& chunk_data() const;
  void set_chunk_data(const std::string& value);
  void set_chunk_data(std::string&& value);
  void set_chunk_data(const char* value);
  void set_chunk_data(const void* value, size_t size);
  std::string* mutable_chunk_data();
  std::string* release_chunk_data();
  void set_allocated_chunk_data(std::string* chunk_data);
  private:
  const std::string& _internal_chunk_data() const;
  void _internal_set_chunk_data(const std::string& value);
  std::string* _internal_mutable_chunk_data();
  public:

  void clear_data();
  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:message.UploadImageRequest)
 private:
  class _Internal;
  void set_has_metadata();
  void set_has_chunk_data();

  inline bool has_data() const;
  inline void clear_has_data();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union DataUnion {
    DataUnion() {}
    ::message::Metadata* metadata_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr chunk_data_;
  } data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class Metadata PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:message.Metadata) */ {
 public:
  inline Metadata() : Metadata(nullptr) {}
  virtual ~Metadata();

  Metadata(const Metadata& from);
  Metadata(Metadata&& from) noexcept
    : Metadata() {
    *this = ::std::move(from);
  }

  inline Metadata& operator=(const Metadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline Metadata& operator=(Metadata&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Metadata& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Metadata* internal_default_instance() {
    return reinterpret_cast<const Metadata*>(
               &_Metadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Metadata& a, Metadata& b) {
    a.Swap(&b);
  }
  inline void Swap(Metadata* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Metadata* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Metadata* New() const final {
    return CreateMaybeMessage<Metadata>(nullptr);
  }

  Metadata* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Metadata>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Metadata& from);
  void MergeFrom(const Metadata& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Metadata* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "message.Metadata";
  }
  protected:
  explicit Metadata(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilenameFieldNumber = 1,
    kMimeTypeFieldNumber = 2,
    kFileSizeFieldNumber = 3,
  };
  // string filename = 1;
  void clear_filename();
  const std::string& filename() const;
  void set_filename(const std::string& value);
  void set_filename(std::string&& value);
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  std::string* mutable_filename();
  std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  private:
  const std::string& _internal_filename() const;
  void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // string mime_type = 2;
  void clear_mime_type();
  const std::string& mime_type() const;
  void set_mime_type(const std::string& value);
  void set_mime_type(std::string&& value);
  void set_mime_type(const char* value);
  void set_mime_type(const char* value, size_t size);
  std::string* mutable_mime_type();
  std::string* release_mime_type();
  void set_allocated_mime_type(std::string* mime_type);
  private:
  const std::string& _internal_mime_type() const;
  void _internal_set_mime_type(const std::string& value);
  std::string* _internal_mutable_mime_type();
  public:

  // int64 file_size = 3;
  void clear_file_size();
  ::PROTOBUF_NAMESPACE_ID::int64 file_size() const;
  void set_file_size(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_file_size() const;
  void _internal_set_file_size(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:message.Metadata)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mime_type_;
  ::PROTOBUF_NAMESPACE_ID::int64 file_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class UploadImageResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:message.UploadImageResponse) */ {
 public:
  inline UploadImageResponse() : UploadImageResponse(nullptr) {}
  virtual ~UploadImageResponse();

  UploadImageResponse(const UploadImageResponse& from);
  UploadImageResponse(UploadImageResponse&& from) noexcept
    : UploadImageResponse() {
    *this = ::std::move(from);
  }

  inline UploadImageResponse& operator=(const UploadImageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline UploadImageResponse& operator=(UploadImageResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UploadImageResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UploadImageResponse* internal_default_instance() {
    return reinterpret_cast<const UploadImageResponse*>(
               &_UploadImageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(UploadImageResponse& a, UploadImageResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(UploadImageResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UploadImageResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UploadImageResponse* New() const final {
    return CreateMaybeMessage<UploadImageResponse>(nullptr);
  }

  UploadImageResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UploadImageResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UploadImageResponse& from);
  void MergeFrom(const UploadImageResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UploadImageResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "message.UploadImageResponse";
  }
  protected:
  explicit UploadImageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStorageUrlFieldNumber = 1,
    kFileIdFieldNumber = 2,
  };
  // string storage_url = 1;
  void clear_storage_url();
  const std::string& storage_url() const;
  void set_storage_url(const std::string& value);
  void set_storage_url(std::string&& value);
  void set_storage_url(const char* value);
  void set_storage_url(const char* value, size_t size);
  std::string* mutable_storage_url();
  std::string* release_storage_url();
  void set_allocated_storage_url(std::string* storage_url);
  private:
  const std::string& _internal_storage_url() const;
  void _internal_set_storage_url(const std::string& value);
  std::string* _internal_mutable_storage_url();
  public:

  // string file_id = 2;
  void clear_file_id();
  const std::string& file_id() const;
  void set_file_id(const std::string& value);
  void set_file_id(std::string&& value);
  void set_file_id(const char* value);
  void set_file_id(const char* value, size_t size);
  std::string* mutable_file_id();
  std::string* release_file_id();
  void set_allocated_file_id(std::string* file_id);
  private:
  const std::string& _internal_file_id() const;
  void _internal_set_file_id(const std::string& value);
  std::string* _internal_mutable_file_id();
  public:

  // @@protoc_insertion_point(class_scope:message.UploadImageResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr storage_url_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UploadImageRequest

// .message.Metadata metadata = 1;
inline bool UploadImageRequest::_internal_has_metadata() const {
  return data_case() == kMetadata;
}
inline bool UploadImageRequest::has_metadata() const {
  return _internal_has_metadata();
}
inline void UploadImageRequest::set_has_metadata() {
  _oneof_case_[0] = kMetadata;
}
inline void UploadImageRequest::clear_metadata() {
  if (_internal_has_metadata()) {
    if (GetArena() == nullptr) {
      delete data_.metadata_;
    }
    clear_has_data();
  }
}
inline ::message::Metadata* UploadImageRequest::release_metadata() {
  // @@protoc_insertion_point(field_release:message.UploadImageRequest.metadata)
  if (_internal_has_metadata()) {
    clear_has_data();
      ::message::Metadata* temp = data_.metadata_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    data_.metadata_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::message::Metadata& UploadImageRequest::_internal_metadata() const {
  return _internal_has_metadata()
      ? *data_.metadata_
      : *reinterpret_cast< ::message::Metadata*>(&::message::_Metadata_default_instance_);
}
inline const ::message::Metadata& UploadImageRequest::metadata() const {
  // @@protoc_insertion_point(field_get:message.UploadImageRequest.metadata)
  return _internal_metadata();
}
inline ::message::Metadata* UploadImageRequest::unsafe_arena_release_metadata() {
  // @@protoc_insertion_point(field_unsafe_arena_release:message.UploadImageRequest.metadata)
  if (_internal_has_metadata()) {
    clear_has_data();
    ::message::Metadata* temp = data_.metadata_;
    data_.metadata_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void UploadImageRequest::unsafe_arena_set_allocated_metadata(::message::Metadata* metadata) {
  clear_data();
  if (metadata) {
    set_has_metadata();
    data_.metadata_ = metadata;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:message.UploadImageRequest.metadata)
}
inline ::message::Metadata* UploadImageRequest::_internal_mutable_metadata() {
  if (!_internal_has_metadata()) {
    clear_data();
    set_has_metadata();
    data_.metadata_ = CreateMaybeMessage< ::message::Metadata >(GetArena());
  }
  return data_.metadata_;
}
inline ::message::Metadata* UploadImageRequest::mutable_metadata() {
  // @@protoc_insertion_point(field_mutable:message.UploadImageRequest.metadata)
  return _internal_mutable_metadata();
}

// bytes chunk_data = 2;
inline bool UploadImageRequest::_internal_has_chunk_data() const {
  return data_case() == kChunkData;
}
inline void UploadImageRequest::set_has_chunk_data() {
  _oneof_case_[0] = kChunkData;
}
inline void UploadImageRequest::clear_chunk_data() {
  if (_internal_has_chunk_data()) {
    data_.chunk_data_.Destroy(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
    clear_has_data();
  }
}
inline const std::string& UploadImageRequest::chunk_data() const {
  // @@protoc_insertion_point(field_get:message.UploadImageRequest.chunk_data)
  return _internal_chunk_data();
}
inline void UploadImageRequest::set_chunk_data(const std::string& value) {
  _internal_set_chunk_data(value);
  // @@protoc_insertion_point(field_set:message.UploadImageRequest.chunk_data)
}
inline std::string* UploadImageRequest::mutable_chunk_data() {
  // @@protoc_insertion_point(field_mutable:message.UploadImageRequest.chunk_data)
  return _internal_mutable_chunk_data();
}
inline const std::string& UploadImageRequest::_internal_chunk_data() const {
  if (_internal_has_chunk_data()) {
    return data_.chunk_data_.Get();
  }
  return *&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void UploadImageRequest::_internal_set_chunk_data(const std::string& value) {
  if (!_internal_has_chunk_data()) {
    clear_data();
    set_has_chunk_data();
    data_.chunk_data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  data_.chunk_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UploadImageRequest::set_chunk_data(std::string&& value) {
  // @@protoc_insertion_point(field_set:message.UploadImageRequest.chunk_data)
  if (!_internal_has_chunk_data()) {
    clear_data();
    set_has_chunk_data();
    data_.chunk_data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  data_.chunk_data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:message.UploadImageRequest.chunk_data)
}
inline void UploadImageRequest::set_chunk_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  if (!_internal_has_chunk_data()) {
    clear_data();
    set_has_chunk_data();
    data_.chunk_data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  data_.chunk_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:message.UploadImageRequest.chunk_data)
}
inline void UploadImageRequest::set_chunk_data(const void* value,
                             size_t size) {
  if (!_internal_has_chunk_data()) {
    clear_data();
    set_has_chunk_data();
    data_.chunk_data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  data_.chunk_data_.Set(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArena());
  // @@protoc_insertion_point(field_set_pointer:message.UploadImageRequest.chunk_data)
}
inline std::string* UploadImageRequest::_internal_mutable_chunk_data() {
  if (!_internal_has_chunk_data()) {
    clear_data();
    set_has_chunk_data();
    data_.chunk_data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return data_.chunk_data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UploadImageRequest::release_chunk_data() {
  // @@protoc_insertion_point(field_release:message.UploadImageRequest.chunk_data)
  if (_internal_has_chunk_data()) {
    clear_has_data();
    return data_.chunk_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void UploadImageRequest::set_allocated_chunk_data(std::string* chunk_data) {
  if (has_data()) {
    clear_data();
  }
  if (chunk_data != nullptr) {
    set_has_chunk_data();
    data_.chunk_data_.UnsafeSetDefault(chunk_data);
    ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena();
    if (arena != nullptr) {
      arena->Own(chunk_data);
    }
  }
  // @@protoc_insertion_point(field_set_allocated:message.UploadImageRequest.chunk_data)
}

inline bool UploadImageRequest::has_data() const {
  return data_case() != DATA_NOT_SET;
}
inline void UploadImageRequest::clear_has_data() {
  _oneof_case_[0] = DATA_NOT_SET;
}
inline UploadImageRequest::DataCase UploadImageRequest::data_case() const {
  return UploadImageRequest::DataCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Metadata

// string filename = 1;
inline void Metadata::clear_filename() {
  filename_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Metadata::filename() const {
  // @@protoc_insertion_point(field_get:message.Metadata.filename)
  return _internal_filename();
}
inline void Metadata::set_filename(const std::string& value) {
  _internal_set_filename(value);
  // @@protoc_insertion_point(field_set:message.Metadata.filename)
}
inline std::string* Metadata::mutable_filename() {
  // @@protoc_insertion_point(field_mutable:message.Metadata.filename)
  return _internal_mutable_filename();
}
inline const std::string& Metadata::_internal_filename() const {
  return filename_.Get();
}
inline void Metadata::_internal_set_filename(const std::string& value) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Metadata::set_filename(std::string&& value) {
  
  filename_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:message.Metadata.filename)
}
inline void Metadata::set_filename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:message.Metadata.filename)
}
inline void Metadata::set_filename(const char* value,
    size_t size) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:message.Metadata.filename)
}
inline std::string* Metadata::_internal_mutable_filename() {
  
  return filename_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Metadata::release_filename() {
  // @@protoc_insertion_point(field_release:message.Metadata.filename)
  return filename_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Metadata::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), filename,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:message.Metadata.filename)
}

// string mime_type = 2;
inline void Metadata::clear_mime_type() {
  mime_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Metadata::mime_type() const {
  // @@protoc_insertion_point(field_get:message.Metadata.mime_type)
  return _internal_mime_type();
}
inline void Metadata::set_mime_type(const std::string& value) {
  _internal_set_mime_type(value);
  // @@protoc_insertion_point(field_set:message.Metadata.mime_type)
}
inline std::string* Metadata::mutable_mime_type() {
  // @@protoc_insertion_point(field_mutable:message.Metadata.mime_type)
  return _internal_mutable_mime_type();
}
inline const std::string& Metadata::_internal_mime_type() const {
  return mime_type_.Get();
}
inline void Metadata::_internal_set_mime_type(const std::string& value) {
  
  mime_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Metadata::set_mime_type(std::string&& value) {
  
  mime_type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:message.Metadata.mime_type)
}
inline void Metadata::set_mime_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  mime_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:message.Metadata.mime_type)
}
inline void Metadata::set_mime_type(const char* value,
    size_t size) {
  
  mime_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:message.Metadata.mime_type)
}
inline std::string* Metadata::_internal_mutable_mime_type() {
  
  return mime_type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Metadata::release_mime_type() {
  // @@protoc_insertion_point(field_release:message.Metadata.mime_type)
  return mime_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Metadata::set_allocated_mime_type(std::string* mime_type) {
  if (mime_type != nullptr) {
    
  } else {
    
  }
  mime_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), mime_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:message.Metadata.mime_type)
}

// int64 file_size = 3;
inline void Metadata::clear_file_size() {
  file_size_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Metadata::_internal_file_size() const {
  return file_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Metadata::file_size() const {
  // @@protoc_insertion_point(field_get:message.Metadata.file_size)
  return _internal_file_size();
}
inline void Metadata::_internal_set_file_size(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  file_size_ = value;
}
inline void Metadata::set_file_size(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_file_size(value);
  // @@protoc_insertion_point(field_set:message.Metadata.file_size)
}

// -------------------------------------------------------------------

// UploadImageResponse

// string storage_url = 1;
inline void UploadImageResponse::clear_storage_url() {
  storage_url_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& UploadImageResponse::storage_url() const {
  // @@protoc_insertion_point(field_get:message.UploadImageResponse.storage_url)
  return _internal_storage_url();
}
inline void UploadImageResponse::set_storage_url(const std::string& value) {
  _internal_set_storage_url(value);
  // @@protoc_insertion_point(field_set:message.UploadImageResponse.storage_url)
}
inline std::string* UploadImageResponse::mutable_storage_url() {
  // @@protoc_insertion_point(field_mutable:message.UploadImageResponse.storage_url)
  return _internal_mutable_storage_url();
}
inline const std::string& UploadImageResponse::_internal_storage_url() const {
  return storage_url_.Get();
}
inline void UploadImageResponse::_internal_set_storage_url(const std::string& value) {
  
  storage_url_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UploadImageResponse::set_storage_url(std::string&& value) {
  
  storage_url_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:message.UploadImageResponse.storage_url)
}
inline void UploadImageResponse::set_storage_url(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  storage_url_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:message.UploadImageResponse.storage_url)
}
inline void UploadImageResponse::set_storage_url(const char* value,
    size_t size) {
  
  storage_url_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:message.UploadImageResponse.storage_url)
}
inline std::string* UploadImageResponse::_internal_mutable_storage_url() {
  
  return storage_url_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UploadImageResponse::release_storage_url() {
  // @@protoc_insertion_point(field_release:message.UploadImageResponse.storage_url)
  return storage_url_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UploadImageResponse::set_allocated_storage_url(std::string* storage_url) {
  if (storage_url != nullptr) {
    
  } else {
    
  }
  storage_url_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), storage_url,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:message.UploadImageResponse.storage_url)
}

// string file_id = 2;
inline void UploadImageResponse::clear_file_id() {
  file_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& UploadImageResponse::file_id() const {
  // @@protoc_insertion_point(field_get:message.UploadImageResponse.file_id)
  return _internal_file_id();
}
inline void UploadImageResponse::set_file_id(const std::string& value) {
  _internal_set_file_id(value);
  // @@protoc_insertion_point(field_set:message.UploadImageResponse.file_id)
}
inline std::string* UploadImageResponse::mutable_file_id() {
  // @@protoc_insertion_point(field_mutable:message.UploadImageResponse.file_id)
  return _internal_mutable_file_id();
}
inline const std::string& UploadImageResponse::_internal_file_id() const {
  return file_id_.Get();
}
inline void UploadImageResponse::_internal_set_file_id(const std::string& value) {
  
  file_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UploadImageResponse::set_file_id(std::string&& value) {
  
  file_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:message.UploadImageResponse.file_id)
}
inline void UploadImageResponse::set_file_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  file_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:message.UploadImageResponse.file_id)
}
inline void UploadImageResponse::set_file_id(const char* value,
    size_t size) {
  
  file_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:message.UploadImageResponse.file_id)
}
inline std::string* UploadImageResponse::_internal_mutable_file_id() {
  
  return file_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UploadImageResponse::release_file_id() {
  // @@protoc_insertion_point(field_release:message.UploadImageResponse.file_id)
  return file_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UploadImageResponse::set_allocated_file_id(std::string* file_id) {
  if (file_id != nullptr) {
    
  } else {
    
  }
  file_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), file_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:message.UploadImageResponse.file_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
