// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf C++ Version: 6.33.4

#ifndef message_2eproto_2epb_2eh
#define message_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_message_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_message_2eproto;
}  // extern "C"
namespace message {
class FileMetadata;
struct FileMetadataDefaultTypeInternal;
extern FileMetadataDefaultTypeInternal _FileMetadata_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FileMetadata_class_data_;
class UploadImageRequest;
struct UploadImageRequestDefaultTypeInternal;
extern UploadImageRequestDefaultTypeInternal _UploadImageRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UploadImageRequest_class_data_;
class UploadImageResponse;
struct UploadImageResponseDefaultTypeInternal;
extern UploadImageResponseDefaultTypeInternal _UploadImageResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UploadImageResponse_class_data_;
}  // namespace message
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace message {

// ===================================================================


// -------------------------------------------------------------------

class UploadImageResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:message.UploadImageResponse) */ {
 public:
  inline UploadImageResponse() : UploadImageResponse(nullptr) {}
  ~UploadImageResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UploadImageResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UploadImageResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UploadImageResponse(::google::protobuf::internal::ConstantInitialized);

  inline UploadImageResponse(const UploadImageResponse& from) : UploadImageResponse(nullptr, from) {}
  inline UploadImageResponse(UploadImageResponse&& from) noexcept
      : UploadImageResponse(nullptr, ::std::move(from)) {}
  inline UploadImageResponse& operator=(const UploadImageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline UploadImageResponse& operator=(UploadImageResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UploadImageResponse& default_instance() {
    return *reinterpret_cast<const UploadImageResponse*>(
        &_UploadImageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(UploadImageResponse& a, UploadImageResponse& b) { a.Swap(&b); }
  inline void Swap(UploadImageResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UploadImageResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UploadImageResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UploadImageResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UploadImageResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UploadImageResponse& from) { UploadImageResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UploadImageResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "message.UploadImageResponse"; }

  explicit UploadImageResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  UploadImageResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const UploadImageResponse& from);
  UploadImageResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, UploadImageResponse&& from) noexcept
      : UploadImageResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStorageUrlFieldNumber = 2,
    kFastdfsGroupFieldNumber = 3,
    kFastdfsPathFieldNumber = 4,
    kFileSizeFieldNumber = 5,
    kErrorFieldNumber = 1,
  };
  // string storage_url = 2;
  void clear_storage_url() ;
  const ::std::string& storage_url() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_storage_url(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_storage_url();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_storage_url();
  void set_allocated_storage_url(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_storage_url() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_storage_url(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_storage_url();

  public:
  // string fastdfs_group = 3;
  void clear_fastdfs_group() ;
  const ::std::string& fastdfs_group() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_fastdfs_group(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_fastdfs_group();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_fastdfs_group();
  void set_allocated_fastdfs_group(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_fastdfs_group() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_fastdfs_group(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_fastdfs_group();

  public:
  // string fastdfs_path = 4;
  void clear_fastdfs_path() ;
  const ::std::string& fastdfs_path() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_fastdfs_path(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_fastdfs_path();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_fastdfs_path();
  void set_allocated_fastdfs_path(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_fastdfs_path() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_fastdfs_path(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_fastdfs_path();

  public:
  // int64 file_size = 5;
  void clear_file_size() ;
  ::int64_t file_size() const;
  void set_file_size(::int64_t value);

  private:
  ::int64_t _internal_file_size() const;
  void _internal_set_file_size(::int64_t value);

  public:
  // int32 error = 1;
  void clear_error() ;
  ::int32_t error() const;
  void set_error(::int32_t value);

  private:
  ::int32_t _internal_error() const;
  void _internal_set_error(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:message.UploadImageResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 72,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const UploadImageResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr storage_url_;
    ::google::protobuf::internal::ArenaStringPtr fastdfs_group_;
    ::google::protobuf::internal::ArenaStringPtr fastdfs_path_;
    ::int64_t file_size_;
    ::int32_t error_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull UploadImageResponse_class_data_;
// -------------------------------------------------------------------

class FileMetadata final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:message.FileMetadata) */ {
 public:
  inline FileMetadata() : FileMetadata(nullptr) {}
  ~FileMetadata() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FileMetadata* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FileMetadata));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FileMetadata(::google::protobuf::internal::ConstantInitialized);

  inline FileMetadata(const FileMetadata& from) : FileMetadata(nullptr, from) {}
  inline FileMetadata(FileMetadata&& from) noexcept
      : FileMetadata(nullptr, ::std::move(from)) {}
  inline FileMetadata& operator=(const FileMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileMetadata& operator=(FileMetadata&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileMetadata& default_instance() {
    return *reinterpret_cast<const FileMetadata*>(
        &_FileMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(FileMetadata& a, FileMetadata& b) { a.Swap(&b); }
  inline void Swap(FileMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileMetadata* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FileMetadata>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FileMetadata& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FileMetadata& from) { FileMetadata::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FileMetadata* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "message.FileMetadata"; }

  explicit FileMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FileMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FileMetadata& from);
  FileMetadata(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FileMetadata&& from) noexcept
      : FileMetadata(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFilenameFieldNumber = 1,
    kMimeTypeFieldNumber = 2,
    kFileSizeFieldNumber = 3,
  };
  // string filename = 1;
  void clear_filename() ;
  const ::std::string& filename() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_filename(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_filename();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_filename();
  void set_allocated_filename(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_filename() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_filename(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_filename();

  public:
  // string mime_type = 2;
  void clear_mime_type() ;
  const ::std::string& mime_type() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_mime_type(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_mime_type();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_mime_type();
  void set_allocated_mime_type(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_mime_type() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_mime_type(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_mime_type();

  public:
  // int64 file_size = 3;
  void clear_file_size() ;
  ::int64_t file_size() const;
  void set_file_size(::int64_t value);

  private:
  ::int64_t _internal_file_size() const;
  void _internal_set_file_size(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:message.FileMetadata)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 46,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FileMetadata& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr filename_;
    ::google::protobuf::internal::ArenaStringPtr mime_type_;
    ::int64_t file_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FileMetadata_class_data_;
// -------------------------------------------------------------------

class UploadImageRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:message.UploadImageRequest) */ {
 public:
  inline UploadImageRequest() : UploadImageRequest(nullptr) {}
  ~UploadImageRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UploadImageRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UploadImageRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UploadImageRequest(::google::protobuf::internal::ConstantInitialized);

  inline UploadImageRequest(const UploadImageRequest& from) : UploadImageRequest(nullptr, from) {}
  inline UploadImageRequest(UploadImageRequest&& from) noexcept
      : UploadImageRequest(nullptr, ::std::move(from)) {}
  inline UploadImageRequest& operator=(const UploadImageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UploadImageRequest& operator=(UploadImageRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UploadImageRequest& default_instance() {
    return *reinterpret_cast<const UploadImageRequest*>(
        &_UploadImageRequest_default_instance_);
  }
  enum DataCase {
    kMetadata = 1,
    kChunkData = 2,
    DATA_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(UploadImageRequest& a, UploadImageRequest& b) { a.Swap(&b); }
  inline void Swap(UploadImageRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UploadImageRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UploadImageRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UploadImageRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UploadImageRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UploadImageRequest& from) { UploadImageRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UploadImageRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "message.UploadImageRequest"; }

  explicit UploadImageRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  UploadImageRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const UploadImageRequest& from);
  UploadImageRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, UploadImageRequest&& from) noexcept
      : UploadImageRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kChunkIndexFieldNumber = 3,
    kTotalChunksFieldNumber = 4,
    kMetadataFieldNumber = 1,
    kChunkDataFieldNumber = 2,
  };
  // int32 chunk_index = 3;
  void clear_chunk_index() ;
  ::int32_t chunk_index() const;
  void set_chunk_index(::int32_t value);

  private:
  ::int32_t _internal_chunk_index() const;
  void _internal_set_chunk_index(::int32_t value);

  public:
  // int32 total_chunks = 4;
  void clear_total_chunks() ;
  ::int32_t total_chunks() const;
  void set_total_chunks(::int32_t value);

  private:
  ::int32_t _internal_total_chunks() const;
  void _internal_set_total_chunks(::int32_t value);

  public:
  // .message.FileMetadata metadata = 1;
  bool has_metadata() const;
  private:
  bool _internal_has_metadata() const;

  public:
  void clear_metadata() ;
  const ::message::FileMetadata& metadata() const;
  [[nodiscard]] ::message::FileMetadata* PROTOBUF_NULLABLE release_metadata();
  ::message::FileMetadata* PROTOBUF_NONNULL mutable_metadata();
  void set_allocated_metadata(::message::FileMetadata* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_metadata(::message::FileMetadata* PROTOBUF_NULLABLE value);
  ::message::FileMetadata* PROTOBUF_NULLABLE unsafe_arena_release_metadata();

  private:
  const ::message::FileMetadata& _internal_metadata() const;
  ::message::FileMetadata* PROTOBUF_NONNULL _internal_mutable_metadata();

  public:
  // bytes chunk_data = 2;
  bool has_chunk_data() const;
  void clear_chunk_data() ;
  const ::std::string& chunk_data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_chunk_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_chunk_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_chunk_data();
  void set_allocated_chunk_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_chunk_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_chunk_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_chunk_data();

  public:
  void clear_data();
  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:message.UploadImageRequest)
 private:
  class _Internal;
  void set_has_metadata();
  void set_has_chunk_data();
  inline bool has_data() const;
  inline void clear_has_data();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 4,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const UploadImageRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t chunk_index_;
    ::int32_t total_chunks_;
    union DataUnion {
      constexpr DataUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::message::FileMetadata* PROTOBUF_NULLABLE metadata_;
      ::google::protobuf::internal::ArenaStringPtr chunk_data_;
    } data_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull UploadImageRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UploadImageRequest

// .message.FileMetadata metadata = 1;
inline bool UploadImageRequest::has_metadata() const {
  return data_case() == kMetadata;
}
inline bool UploadImageRequest::_internal_has_metadata() const {
  return data_case() == kMetadata;
}
inline void UploadImageRequest::set_has_metadata() {
  _impl_._oneof_case_[0] = kMetadata;
}
inline void UploadImageRequest::clear_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (data_case() == kMetadata) {
    if (GetArena() == nullptr) {
      delete _impl_.data_.metadata_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.data_.metadata_);
    }
    clear_has_data();
  }
}
inline ::message::FileMetadata* PROTOBUF_NULLABLE UploadImageRequest::release_metadata() {
  // @@protoc_insertion_point(field_release:message.UploadImageRequest.metadata)
  if (data_case() == kMetadata) {
    clear_has_data();
    auto* temp = _impl_.data_.metadata_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.data_.metadata_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::message::FileMetadata& UploadImageRequest::_internal_metadata() const {
  return data_case() == kMetadata ? static_cast<const ::message::FileMetadata&>(*_impl_.data_.metadata_)
                     : reinterpret_cast<const ::message::FileMetadata&>(::message::_FileMetadata_default_instance_);
}
inline const ::message::FileMetadata& UploadImageRequest::metadata() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:message.UploadImageRequest.metadata)
  return _internal_metadata();
}
inline ::message::FileMetadata* PROTOBUF_NULLABLE UploadImageRequest::unsafe_arena_release_metadata() {
  // @@protoc_insertion_point(field_unsafe_arena_release:message.UploadImageRequest.metadata)
  if (data_case() == kMetadata) {
    clear_has_data();
    auto* temp = _impl_.data_.metadata_;
    _impl_.data_.metadata_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void UploadImageRequest::unsafe_arena_set_allocated_metadata(
    ::message::FileMetadata* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_data();
  if (value) {
    set_has_metadata();
    _impl_.data_.metadata_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:message.UploadImageRequest.metadata)
}
inline ::message::FileMetadata* PROTOBUF_NONNULL UploadImageRequest::_internal_mutable_metadata() {
  if (data_case() != kMetadata) {
    clear_data();
    set_has_metadata();
    _impl_.data_.metadata_ = 
        ::google::protobuf::Message::DefaultConstruct<::message::FileMetadata>(GetArena());
  }
  return _impl_.data_.metadata_;
}
inline ::message::FileMetadata* PROTOBUF_NONNULL UploadImageRequest::mutable_metadata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::message::FileMetadata* _msg = _internal_mutable_metadata();
  // @@protoc_insertion_point(field_mutable:message.UploadImageRequest.metadata)
  return _msg;
}

// bytes chunk_data = 2;
inline bool UploadImageRequest::has_chunk_data() const {
  return data_case() == kChunkData;
}
inline void UploadImageRequest::set_has_chunk_data() {
  _impl_._oneof_case_[0] = kChunkData;
}
inline void UploadImageRequest::clear_chunk_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (data_case() == kChunkData) {
    _impl_.data_.chunk_data_.Destroy();
    clear_has_data();
  }
}
inline const ::std::string& UploadImageRequest::chunk_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:message.UploadImageRequest.chunk_data)
  return _internal_chunk_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void UploadImageRequest::set_chunk_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (data_case() != kChunkData) {
    clear_data();

    set_has_chunk_data();
    _impl_.data_.chunk_data_.InitDefault();
  }
  _impl_.data_.chunk_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:message.UploadImageRequest.chunk_data)
}
inline ::std::string* PROTOBUF_NONNULL UploadImageRequest::mutable_chunk_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  if (data_case() != kChunkData) {
    clear_data();

    set_has_chunk_data();
    _impl_.data_.chunk_data_.InitDefault();
  }
  ::std::string* _s = _internal_mutable_chunk_data();
  // @@protoc_insertion_point(field_mutable:message.UploadImageRequest.chunk_data)
  return _s;
}
inline const ::std::string& UploadImageRequest::_internal_chunk_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  if (data_case() != kChunkData) {
    return ::google::protobuf::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.data_.chunk_data_.Get();
}
inline void UploadImageRequest::_internal_set_chunk_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.chunk_data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL UploadImageRequest::_internal_mutable_chunk_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.chunk_data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE UploadImageRequest::release_chunk_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:message.UploadImageRequest.chunk_data)
  if (data_case() != kChunkData) {
    return nullptr;
  }
  clear_has_data();
  return _impl_.data_.chunk_data_.Release();
}
inline void UploadImageRequest::set_allocated_chunk_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (has_data()) {
    clear_data();
  }
  if (value != nullptr) {
    set_has_chunk_data();
    _impl_.data_.chunk_data_.InitAllocated(value, GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:message.UploadImageRequest.chunk_data)
}

// int32 chunk_index = 3;
inline void UploadImageRequest::clear_chunk_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_index_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t UploadImageRequest::chunk_index() const {
  // @@protoc_insertion_point(field_get:message.UploadImageRequest.chunk_index)
  return _internal_chunk_index();
}
inline void UploadImageRequest::set_chunk_index(::int32_t value) {
  _internal_set_chunk_index(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:message.UploadImageRequest.chunk_index)
}
inline ::int32_t UploadImageRequest::_internal_chunk_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chunk_index_;
}
inline void UploadImageRequest::_internal_set_chunk_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_index_ = value;
}

// int32 total_chunks = 4;
inline void UploadImageRequest::clear_total_chunks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_chunks_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t UploadImageRequest::total_chunks() const {
  // @@protoc_insertion_point(field_get:message.UploadImageRequest.total_chunks)
  return _internal_total_chunks();
}
inline void UploadImageRequest::set_total_chunks(::int32_t value) {
  _internal_set_total_chunks(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:message.UploadImageRequest.total_chunks)
}
inline ::int32_t UploadImageRequest::_internal_total_chunks() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_chunks_;
}
inline void UploadImageRequest::_internal_set_total_chunks(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_chunks_ = value;
}

inline bool UploadImageRequest::has_data() const {
  return data_case() != DATA_NOT_SET;
}
inline void UploadImageRequest::clear_has_data() {
  _impl_._oneof_case_[0] = DATA_NOT_SET;
}
inline UploadImageRequest::DataCase UploadImageRequest::data_case() const {
  return UploadImageRequest::DataCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// FileMetadata

// string filename = 1;
inline void FileMetadata::clear_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& FileMetadata::filename() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:message.FileMetadata.filename)
  return _internal_filename();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileMetadata::set_filename(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.filename_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:message.FileMetadata.filename)
}
inline ::std::string* PROTOBUF_NONNULL FileMetadata::mutable_filename()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:message.FileMetadata.filename)
  return _s;
}
inline const ::std::string& FileMetadata::_internal_filename() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filename_.Get();
}
inline void FileMetadata::_internal_set_filename(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileMetadata::_internal_mutable_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.filename_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileMetadata::release_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:message.FileMetadata.filename)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.filename_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.filename_.Set("", GetArena());
  }
  return released;
}
inline void FileMetadata::set_allocated_filename(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.filename_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:message.FileMetadata.filename)
}

// string mime_type = 2;
inline void FileMetadata::clear_mime_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mime_type_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& FileMetadata::mime_type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:message.FileMetadata.mime_type)
  return _internal_mime_type();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileMetadata::set_mime_type(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.mime_type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:message.FileMetadata.mime_type)
}
inline ::std::string* PROTOBUF_NONNULL FileMetadata::mutable_mime_type()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_mime_type();
  // @@protoc_insertion_point(field_mutable:message.FileMetadata.mime_type)
  return _s;
}
inline const ::std::string& FileMetadata::_internal_mime_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mime_type_.Get();
}
inline void FileMetadata::_internal_set_mime_type(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mime_type_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileMetadata::_internal_mutable_mime_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.mime_type_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileMetadata::release_mime_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:message.FileMetadata.mime_type)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.mime_type_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.mime_type_.Set("", GetArena());
  }
  return released;
}
inline void FileMetadata::set_allocated_mime_type(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.mime_type_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.mime_type_.IsDefault()) {
    _impl_.mime_type_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:message.FileMetadata.mime_type)
}

// int64 file_size = 3;
inline void FileMetadata::clear_file_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_size_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int64_t FileMetadata::file_size() const {
  // @@protoc_insertion_point(field_get:message.FileMetadata.file_size)
  return _internal_file_size();
}
inline void FileMetadata::set_file_size(::int64_t value) {
  _internal_set_file_size(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:message.FileMetadata.file_size)
}
inline ::int64_t FileMetadata::_internal_file_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_size_;
}
inline void FileMetadata::_internal_set_file_size(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_size_ = value;
}

// -------------------------------------------------------------------

// UploadImageResponse

// int32 error = 1;
inline void UploadImageResponse::clear_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t UploadImageResponse::error() const {
  // @@protoc_insertion_point(field_get:message.UploadImageResponse.error)
  return _internal_error();
}
inline void UploadImageResponse::set_error(::int32_t value) {
  _internal_set_error(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:message.UploadImageResponse.error)
}
inline ::int32_t UploadImageResponse::_internal_error() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_;
}
inline void UploadImageResponse::_internal_set_error(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = value;
}

// string storage_url = 2;
inline void UploadImageResponse::clear_storage_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_url_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& UploadImageResponse::storage_url() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:message.UploadImageResponse.storage_url)
  return _internal_storage_url();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void UploadImageResponse::set_storage_url(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.storage_url_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:message.UploadImageResponse.storage_url)
}
inline ::std::string* PROTOBUF_NONNULL UploadImageResponse::mutable_storage_url()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_storage_url();
  // @@protoc_insertion_point(field_mutable:message.UploadImageResponse.storage_url)
  return _s;
}
inline const ::std::string& UploadImageResponse::_internal_storage_url() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.storage_url_.Get();
}
inline void UploadImageResponse::_internal_set_storage_url(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_url_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL UploadImageResponse::_internal_mutable_storage_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.storage_url_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE UploadImageResponse::release_storage_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:message.UploadImageResponse.storage_url)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.storage_url_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.storage_url_.Set("", GetArena());
  }
  return released;
}
inline void UploadImageResponse::set_allocated_storage_url(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.storage_url_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.storage_url_.IsDefault()) {
    _impl_.storage_url_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:message.UploadImageResponse.storage_url)
}

// string fastdfs_group = 3;
inline void UploadImageResponse::clear_fastdfs_group() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fastdfs_group_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& UploadImageResponse::fastdfs_group() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:message.UploadImageResponse.fastdfs_group)
  return _internal_fastdfs_group();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void UploadImageResponse::set_fastdfs_group(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.fastdfs_group_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:message.UploadImageResponse.fastdfs_group)
}
inline ::std::string* PROTOBUF_NONNULL UploadImageResponse::mutable_fastdfs_group()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_fastdfs_group();
  // @@protoc_insertion_point(field_mutable:message.UploadImageResponse.fastdfs_group)
  return _s;
}
inline const ::std::string& UploadImageResponse::_internal_fastdfs_group() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fastdfs_group_.Get();
}
inline void UploadImageResponse::_internal_set_fastdfs_group(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fastdfs_group_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL UploadImageResponse::_internal_mutable_fastdfs_group() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.fastdfs_group_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE UploadImageResponse::release_fastdfs_group() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:message.UploadImageResponse.fastdfs_group)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.fastdfs_group_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fastdfs_group_.Set("", GetArena());
  }
  return released;
}
inline void UploadImageResponse::set_allocated_fastdfs_group(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.fastdfs_group_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fastdfs_group_.IsDefault()) {
    _impl_.fastdfs_group_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:message.UploadImageResponse.fastdfs_group)
}

// string fastdfs_path = 4;
inline void UploadImageResponse::clear_fastdfs_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fastdfs_path_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& UploadImageResponse::fastdfs_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:message.UploadImageResponse.fastdfs_path)
  return _internal_fastdfs_path();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void UploadImageResponse::set_fastdfs_path(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.fastdfs_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:message.UploadImageResponse.fastdfs_path)
}
inline ::std::string* PROTOBUF_NONNULL UploadImageResponse::mutable_fastdfs_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_fastdfs_path();
  // @@protoc_insertion_point(field_mutable:message.UploadImageResponse.fastdfs_path)
  return _s;
}
inline const ::std::string& UploadImageResponse::_internal_fastdfs_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fastdfs_path_.Get();
}
inline void UploadImageResponse::_internal_set_fastdfs_path(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fastdfs_path_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL UploadImageResponse::_internal_mutable_fastdfs_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.fastdfs_path_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE UploadImageResponse::release_fastdfs_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:message.UploadImageResponse.fastdfs_path)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.fastdfs_path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fastdfs_path_.Set("", GetArena());
  }
  return released;
}
inline void UploadImageResponse::set_allocated_fastdfs_path(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.fastdfs_path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fastdfs_path_.IsDefault()) {
    _impl_.fastdfs_path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:message.UploadImageResponse.fastdfs_path)
}

// int64 file_size = 5;
inline void UploadImageResponse::clear_file_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_size_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int64_t UploadImageResponse::file_size() const {
  // @@protoc_insertion_point(field_get:message.UploadImageResponse.file_size)
  return _internal_file_size();
}
inline void UploadImageResponse::set_file_size(::int64_t value) {
  _internal_set_file_size(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:message.UploadImageResponse.file_size)
}
inline ::int64_t UploadImageResponse::_internal_file_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_size_;
}
inline void UploadImageResponse::_internal_set_file_size(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_size_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace message


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // message_2eproto_2epb_2eh
