// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto

#include "message.pb.h"
#include "message.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace message {

static const char* StorageService_method_names[] = {
  "/message.StorageService/UploadImage",
};

std::unique_ptr< StorageService::Stub> StorageService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StorageService::Stub> stub(new StorageService::Stub(channel));
  return stub;
}

StorageService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_UploadImage_(StorageService_method_names[0], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::message::UploadImageRequest>* StorageService::Stub::UploadImageRaw(::grpc::ClientContext* context, ::message::UploadImageResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::message::UploadImageRequest>::Create(channel_.get(), rpcmethod_UploadImage_, context, response);
}

void StorageService::Stub::experimental_async::UploadImage(::grpc::ClientContext* context, ::message::UploadImageResponse* response, ::grpc::experimental::ClientWriteReactor< ::message::UploadImageRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::message::UploadImageRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_UploadImage_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::message::UploadImageRequest>* StorageService::Stub::AsyncUploadImageRaw(::grpc::ClientContext* context, ::message::UploadImageResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::message::UploadImageRequest>::Create(channel_.get(), cq, rpcmethod_UploadImage_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::message::UploadImageRequest>* StorageService::Stub::PrepareAsyncUploadImageRaw(::grpc::ClientContext* context, ::message::UploadImageResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::message::UploadImageRequest>::Create(channel_.get(), cq, rpcmethod_UploadImage_, context, response, false, nullptr);
}

StorageService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< StorageService::Service, ::message::UploadImageRequest, ::message::UploadImageResponse>(
          [](StorageService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::message::UploadImageRequest>* reader,
             ::message::UploadImageResponse* resp) {
               return service->UploadImage(ctx, reader, resp);
             }, this)));
}

StorageService::Service::~Service() {
}

::grpc::Status StorageService::Service::UploadImage(::grpc::ServerContext* context, ::grpc::ServerReader< ::message::UploadImageRequest>* reader, ::message::UploadImageResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message

