CREATE TABLE artists (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '歌手ID',
  name VARCHAR(255) NOT NULL COMMENT '歌手名称',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uniq_artist_name (name) COMMENT '歌手名称唯一索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='歌手信息表';
