CREATE TABLE songs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '歌曲ID',
  title VARCHAR(255) NOT NULL COMMENT '歌曲名称',
  album_id INT UNSIGNED NOT NULL COMMENT '所属专辑ID',
  duration INT UNSIGNED NOT NULL COMMENT '时长（秒）',
  track_number SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '专辑中的曲目顺序',
  file_url VARCHAR(512) NOT NULL COMMENT '歌曲文件URL',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  
  FOREIGN KEY (album_id) REFERENCES albums(id) ON DELETE CASCADE,
  INDEX idx_song_title (title),
  INDEX idx_track_number (track_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='歌曲信息表';
